name: Trap
main: io.github.yehan2002.Traps.Main
version: 1.2beta
commands:
  trap:
    description: Traps and Trolls Main Command
    usage: /trap help

permissions:
  trapAandTrolls.exempt:
    description: Players with this permision do not trigger any traps.
    default: false
