name: Trap
main: io.github.yehan2002.Traps.Main
version: 1.2
commands:
  trap:
    description: Traps and Trolls Main Command
    usage: /trap help

#permissions:
#  trapAndTrolls.exempt:
#    description: Players with this permision do not trigger any traps.
#    default: false

#  trapsAndTrolls.show:
#    description: Allows players to user /trap show
#    default: false
